spring:
  datasource:
    #    locally
    #url: jdbc:postgresql://localhost:5432/wishlist_dev
    #username: postgres
    #password: postgres
    url: jdbc:postgresql://localhost:5432/lexiscan_dev
    username: admin
    password: 123qwe
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    change-log: classpath:database/changelog/InitialMigration.xml
    enabled: true
    drop-first: false
    default-schema: public
  thymeleaf:
    cache: false
  application:
    name: lexiscan-auth
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# метрики доступны здесь http://localhost:8181/actuator/prometheus
# source: https://habr.com/ru/articles/548700/
management:
  endpoints:
    web:
      exposure:
#        add info, metrics
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

model:
  url: "http://localhost:8080/ml-model/count"

storage:
  url: jdbc:postgresql://localhost:5432/lexiscan_dev
  username: admin
  password: 123qwe

server:
  port: 8181

swagger:
  url: "http://localhost:8181"

# test data, differs from the production one, that is written in secrets
s3:
  key-id: "paste your key"
  secret-key: "paste your key"
  region: "ru-central1"
  s3-endpoint: "https://storage.yandexcloud.net"
  bucket: "bakhankova-hse"

jwt-security:
  key: "paste your key"