server:
  port: 8086
  #  in bytes
  max-http-request-header-size: 1073741824

spring:
  application:
    name: lexiscan-app
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  uploadingDirectory: photos

